### ISSUE TITLE
Does not seem to work with react-router

### ISSUE THREAD

**Issue by josiahgallen** [open-source-labs/reactime#145]
When following the set up instructions provided in the README this tool breaks the application if the app has `react-router-dom`. Currently using react-router-dom `v5.1.2`.

I see this error when attempting to include in my project.
<img width="779" alt="Screen Shot 2019-10-10 at 8 32 27 PM" src="https://user-images.githubusercontent.com/10858913/66618048-3dc19380-eb9d-11e9-8a99-1a654904ffef.png">

Seems like `acorn` is choking on something in router... I am unsure if acorn was pulled in as a dependency of `reactime` or another one of the packages i have in my project... regardless, when i comment out the router code reactime works, when i have it in the code it breaks.

**Comment by AndyWongDev** [comment]
Thank you for reporting this, since this was missed in our original testing, to clarify, did your React router crash on runtime or only after clicking on your Components?

**Comment by mikestaub** [comment]
I also hit this error, the app crashes immediately before any user interaction.

**Comment by RajeebTheGreat** [comment]
Hi @josiahgallen, @mikestaub 

We just released Reactime 3.0 which supports React Router. Update both the npm package and Chrome extension and let me know if it works for you.
