### ISSUE TITLE
Cannot read property '_internalRoot' of undefined

### ISSUE THREAD

**Issue by dangus21** [open-source-labs/reactime#151]
I get this error in the console: 
![image](https://user-images.githubusercontent.com/3925278/69247799-f28a9f80-0ba2-11ea-88dc-ec78c5a30a75.png)

The add on tab on the dev tools says it doesn't find any active react project

**Comment by chriswillsflannery** [comment]
Are you working with a demo app that uses concurrent mode? That looks like an error that would occur when improperly wrapping the call to reactime(). Please refer to the readme and let us know if the problem persists!

**Comment by dangus21** [comment]
the app uses react 15, is that the problem?

**Comment by chriswillsflannery** [comment]
Yup - since the tree traversal relies on React Fiber to construct the trees, you'll need to work with 16.0 or later. Closing this issue but feel free to open another if you run into any more issues! cheers, 3.0 team
