### ISSUE TITLE
Uncaught DOMException ... could not be cloned.

### ISSUE THREAD

**Issue by itzsaga** [open-source-labs/reactime#152]
`pacakge.json`
```
"react": "^16.11.0",
"react-dom": "^16.11.0",
"reactime": "^3.0.2"
```

Setup exactly like the docs specify with `reactime(rootContainer)` I throw this error:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': client => {
      this.setState({
        client
      });
    } could not be cloned.
    at sendSnapshot (http://localhost:3000/static/js/1.chunk.js:98591:12)
    at http://localhost:3000/static/js/1.chunk.js:98734:46
sendSnapshot @ linkFiber.js:29
(anonymous) @ linkFiber.js:172
postMessage (async)
282 @ content.bundle.js:1
n @ content.bundle.js:1
(anonymous) @ content.bundle.js:1
(anonymous) @ content.bundle.js:1
```

When I remove `reactime(rootContainer)` all is well.

**Comment by chriswillsflannery** [comment]
Hey Seth, are you using an app with concurrent mode?

**Comment by itzsaga** [comment]
@chriswillsflannery I am not.

**Comment by martinschayna** [comment]
I have reached very similar exception:

```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': class RootComponent extends abra_platform__WEBPACK_IMPORTED_MODULE_4__["Component"] {
  static initModel(_initD...<omitted>...
} could not be cloned.
```

The app is bundled by Webpack and my components have two or three levels of inheritance with many static methods (here initModel is one of them). Also I'm on React 16.8.6 thus no concurrent mode.

**Comment by chriswillsflannery** [comment]
Hmm... hard to identify this issue without seeing the demo app. Is it public?

**Comment by goransm** [comment]
We're having the same problem, seems to be related to a dynamic import of a component?

![image](https://user-images.githubusercontent.com/2332171/69415819-9ac07580-0d15-11ea-9424-f4fbc22cb3ed.png)

**Comment by mikeLspohn** [comment]
asyncToGenerator.js?b775:6 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function (action) {
        if (typeof action === 'function') {
          return action(dispatch, getState, ext...<omitted>... } could not be cloned.

**Comment by davidchai717** [comment]
Looks to be a problem with the copy of the component tree that's being sent to our pub-sub system.

As per @goransm 's situation, there might be some components with features we haven't accounted for (dynamic import/static method). To help further debugging, it would be helpful to confirm whether you are using these specific features.

**Comment by itzsaga** [comment]
@chriswillsflannery and @davidchai717 thanks for the info. I can't share code but I'll see if I can replicate with a demo app. I'm slowly copying/pasting and making generic the app into a CodeSandbox but anything in particular that might tip the scales? I'm not doing any dynamic imports. Using `React.lazy()` but that isn't throwing an error in the sandbox.

**Comment by davidchai717** [comment]
@itzsaga if I understood you correctly, you are using React.lazy in the sandbox but it works just fine still? If so can you detail any other discrepancies between the sandbox and the actual code (to your comfort level)?

**Comment by itzsaga** [comment]
@davidchai717 that is correct. I'm still working to add components bit by bit to hopefully find when it fails. Might take a few days but wanted to let you know I was doing that to hopefully pin down what causes the error. When I get it to error I'll share the sandbox link.

**Comment by davidchai717** [comment]
@itzsaga sounds great. Much appreciated and keep us posted.

**Comment by kevinfey** [comment]
Closing this issue do to thread inactivity.
