### ISSUE TITLE
"Map" tab view only works on Recoil-based target applications

### ISSUE THREAD

**Issue by haejinjo** [open-source-labs/reactime#204]
Does not work on vanilla react app:
![image](https://user-images.githubusercontent.com/23015394/90461574-80a49f80-e0bb-11ea-9514-6fc59deee470.png)

Works on codesmith homepage:
![image](https://user-images.githubusercontent.com/23015394/90461620-a6ca3f80-e0bb-11ea-8429-b0aba8d6f333.png)

**Comment by kevinfey** [comment]
Issue fixed in Reactime 5.0
