### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by haejinjo** [open-source-labs/reactime#205]
![image](https://user-images.githubusercontent.com/23015394/90700769-83c69980-e23b-11ea-8cca-78d34b75458b.png)

This error (pictured above) shows up on the main browser console (not the Reactime extension console) occasionally, not always.
Still not sure what causes it, or what functionality exactly is affected, if any at all.

The previous iteration team seemed to attempt solving this issue by returning `true` at the end of the `port.onMessage` and `chrome.runtime.onMessage` event handlers in our `background.js` script file. 
One of these attempts is reproduced in screenshot-form, below:
![image](https://user-images.githubusercontent.com/23015394/90701117-7231c180-e23c-11ea-84f3-9c32f1228e3e.png)

**Why it might be happening?**
Issue #206 : an uncaught error in our extension that breaks the chrome runtime connection.

**Comment by kevinfey** [comment]
This issue does not come up in the package version on the Chrome package. Issue came from updating unpacked chrome dev tool during development.
