### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src github.githubassets.com".

### ISSUE THREAD

**Issue by haejinjo** [open-source-labs/reactime#206]
![image](https://user-images.githubusercontent.com/23015394/90701238-c2a91f00-e23c-11ea-8975-17a70115c7d3.png)

This unsafe-eval error appears repeatedly in the logs of our Reactime package in the extensions manager.

The only place in the codebase I could find relating to `unsafe-eval` was in our `manifest.json`, reproduced below:
![image](https://user-images.githubusercontent.com/23015394/90701307-ecfadc80-e23c-11ea-89ad-be9af0a31934.png)

**Comment by kevinfey** [comment]
Resolved in production build.
