### ISSUE TITLE
Cannot read property 'nodeToNodeSubscriptions' of undefined

### ISSUE THREAD

**Issue by joraycorn** [open-source-labs/reactime#216]
Hey guys ! 

Just trying to get the extension to work on one of my project... keep getting a 
`Cannot read property 'nodeToNodeSubscriptions' of undefined` even tho I got the ReactDevTool installed.

![image](https://user-images.githubusercontent.com/53843408/92545119-750d4a00-f21d-11ea-8ecf-a0406a1ee39a.png)

Is there anything I need to do make it work  ?
Thanks !

**Comment by kevinfey** [comment]
Hi joraycorn - can You link to the repo where You're having this issue?

**Comment by JohannesKlauss** [comment]
@kevinfey This happens when using SSR. The extension uses a lot of `window` calls which then returns undefined. You'd have to sanity check every `window` to make is compatible with something like Next.js

**Comment by lind-tania** [comment]
hi, 
Now Reactime is compatible with Next.js. To test it - run your app in development mode with Reactime.
