### ISSUE TITLE
This extension causes a lot of slugginess with real time data (a relatively big amount)

### ISSUE THREAD

**Issue by pitops** [open-source-labs/reactime#218]
I thought we had a memory leak at work but after trying in incognito the problem was gone. 

I remembered i installed this extension on saturday and when i got to work today(yes we work sundays) the app felt really sluggish.

When i disabled the extension everything was back to normal.

There were memory spikes e.g from 80mb to 250mb and down again.

**Comment by JackC27** [comment]
Hello, 
Do you notice this leak with Recoil apps? Recoil just released v0.0.12 that addresses a potential memory leak. Are you able to reproduce the issue?

**Comment by pitops** [comment]
Hi,

No, we are not using recoil I am afraid. We used the redux pattern using context.

**Comment by lind-tania** [comment]
Hi,
We recently updated Reactime. The main issue with the memory leak was connected with production mode. Now Reactime running only in development mode and it is much faster.
