### ISSUE TITLE
Not able to switch back to previous state after persisting 

### ISSUE THREAD

**Issue by Raunak-Agrawal** [open-source-labs/reactime#219]
When i do persist my current snapshot of the state, and when i do refresh, the snapshot shows in the reacttime panel, but I am not able to Jump to that particular state in time. I can only see my previous states but can't jump back to them.

**Comment by kevinfey** [comment]
Hi Raunak,

What type of state managment are You using for your application?

**Comment by Raunak-Agrawal** [comment]
Hi Kevin,

I am using React hooks to manage my manage my state.

**Comment by kevinfey** [comment]
Thanks – I'll take a look at our dispatch function for hooks.

**Comment by lind-tania** [comment]
Hi Raunak, 
Reactime was recently updated, now it's running only in dev mode and it's compatible with Hooks.
