### ISSUE TITLE
Accessor not supported

### ISSUE THREAD

**Issue by RussellBloxwich** [open-source-labs/reactime#224]
With this extension enabled in Chrome 86.0.4240.111 on Windows 10 1903, Youtube (for example, it may also happen on other sites) throws an "Accessor not supported" error repeatedly, making the site nearly unusable. No idea whats going on, but I suspect reactime isn't correctly identifying the page as angular and not react.

Apologies for the less than ideal issue.

**Comment by lind-tania** [comment]
Hi! The new version of Reactime works only in development mode.
