### ISSUE TITLE
False parsing of ArrayPattern

### ISSUE THREAD

**Issue by anilanar** [open-source-labs/reactime#225]
https://github.com/open-source-labs/reactime/blob/37ae68c5615f44a977fb08137adedf709b472353/src/backend/helpers.ts#L107-L114

The above code breaks for the following case:

```
const [, setState] = useFoo();
```

because `hook.id.elements[0]` is `null` with the above pattern match. `hook.name` will crash.

**Comment by rtviner** [comment]
Hi @anilanar,

Thanks for bringing this to our attention, we are looking into it.

Could you possibly link to the repo where you're having this issue?

Thanks!

**Comment by anilanar** [comment]
@rtviner I cannot. If `const [, setState] = useFoo();` is not reproducable, feel free to close.

**Comment by aspiers** [comment]
This should be easy to fix.  See https://github.com/open-source-labs/reactime/pull/261 for a fix for a similar issue in the same part of the code.

**Comment by jemzir** [comment]
Already found a fix in a prior branch and merged in from a prior contributor see #261 thread
