### ISSUE TITLE
TypeError: Cannot read property 'object' of null in backend.bundle.js

### ISSUE THREAD

**Issue by ali-master** [open-source-labs/reactime#230]
Hi there

I just installed the extension and I got this error when I open my React application in development mode.
![image](https://user-images.githubusercontent.com/9049092/102316633-8cca3c00-3f8b-11eb-8951-6b16b0f58645.png)

More details:
- Redux v4.0.5
- Redux-Saga v1.1.3
- React-Redux v7.1.3
- React v17.0.1

**Comment by jafin** [comment]
Same error, compared to OP,   I only have React 17.0.1 , no Redux.

**Comment by lpillonel** [comment]
I am facing the exact same error, with same stack

**Comment by bduff9** [comment]
Same error, using NextJS 11.0.1 and react 17.0.2.  Was driving me crazy until I found this issue.

**Comment by bhuddleston-biocorellc** [comment]
I am also running into this issue. Would greatly appreciate it if someone could look into this.

**Comment by iMakedonsky** [comment]
Same issue with react, mobx, mobx-state-tree

**Comment by aspiers** [comment]
The error given isn't really enough to pin this down. Please click on the link to the exact source within the bundle, and provide that or a minimally reproducible test case.
