### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by xstable** [open-source-labs/reactime#233]
If I activate REACTIME at my nextjs Page, I got this and REACTIME doesn't work.
![image](https://user-images.githubusercontent.com/1778068/104818176-3704e000-5826-11eb-9e51-479d017e3e79.png)

If I deactivate it, page work like expected like before.

**Comment by bentron2000** [comment]
I also have this issue

**Comment by aspiers** [comment]
The error given isn't really enough to pin this down. Please click on the link to the exact source within the bundle, and provide that or a minimally reproducible test case.

If you follow the instructions in #255 then you can get the same error with non-minified version of this source, and even set breakpoints to find out what is `undefined`.
