### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by maxbarry** [open-source-labs/reactime#238]
Reactime works for some of my React projects but one errors out upon startup:

![Screenshot from 2021-02-25 20-02-29](https://user-images.githubusercontent.com/892447/109129390-b500c300-77a4-11eb-8821-e0074b1c440d.png)

...which is this:

![Screenshot from 2021-02-25 20-02-11](https://user-images.githubusercontent.com/892447/109129413-bb8f3a80-77a4-11eb-878e-ff85516215cb.png)

This is with:
├─ react@17.0.1
└─ recoil@0.1.2

The projects that do work are older versions using React 16.13.1 and without Recoil.

**Comment by aspiers** [comment]
If you follow the instructions in #255 then you can get the same error with non-minified version of this source, and even set breakpoints to find out why `A.stateNode.classList` is `undefined`.

**Comment by Jennamaree** [comment]
Taskkill
