### ISSUE TITLE
Reactime v7.0.0 (repo) vs v8.0.0 (Chrome web store)?

### ISSUE THREAD

**Issue by cweekly** [open-source-labs/reactime#246]
The latest tag in the repo is 7.0.0 (Oct 30, 2020) but the Chrome web store advertises 8.0.0 (Feb 6, 2021). 

Where did the published v8.0.0 come from?

Please and thanks.

**Comment by wrenchingdev** [comment]
Looking at the Chrome web store now, the version published is listed as 9.0.0. Is this just a mistake when pushing to the store?

**Comment by aspiers** [comment]
It's now 11.0.0.  Apparently whoever is doing releases is not creating tags here in GitHub, which is somewhat unfortunate.  Would be great if this was fixed.

**Comment by aspiers** [comment]
Ahah, it was bumped to 11.0.0 in #252. @liuedar Please could you add corresponding tags? Thanks a lot!
